### ISSUE TITLE
[Fixed in ver 302] - Floating main menu doesn't always auto-hide on starting FF

### ISSUE THREAD

**Issue by gene-pavlovsky** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#292]
When I just start FF, the floating main menu is visible (at somewhat wrong position)
![main-menu](http://i.imgur.com/DUbdW3V.png)

Since there are usually a bunch of tabs to restore from the last session, FF slows down, almost freezes, for several seconds, before all the tabs are restored. After that, usually the floating main menu auto-hides, but sometimes it remains floating at this wrong position. Moving the mouse cursor over the "F" button in the top-left corner, then out, hides the main menu.

What I expected is: main menu not showing at all when starting FF. Only shown when hovering the mouse cursor over the "F" button.

**Comment by Javier-DarthPalpatine** [comment]
This is hopefully fixed in ver 302.  Please confirm if this is your case too. A good test will be with a long Fx  startup like you described.

**Comment by gene-pavlovsky** [comment]
Appears to be fixed. Can't reproduce anymore. I'll post if it happens again.
Thanks!
