### ISSUE TITLE
[FIXED in ver 303] - Unclickable buttons

### ISSUE THREAD

**Issue by sanya-rnd** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#293]
User-agent request header (userAgent)	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:42.0) 
HCTP 3.0.2rc

Unclickable minimize/maximize/close buttons with new top edge internal styling and default button view.

**Comment by Gaffer13** [comment]
I believe I have a related issue - a conflict with Tree Style Tab:

Min, Max, Close buttons disappear immediately or after restart when system title bar is set to always hidden, button styling is set to default, and top edge styling is set to new style. The buttons appear after you enter and exit Firefox UI customization. 

Buttons behave normally with top edge styling set to Legacy.

Windows 10 x64, Firefox 40.0.3, HCTP 3.0.2

**Comment by Javier-DarthPalpatine** [comment]
This is hopefully FIXED in all cases in new version 303rc & 303 ! 
Please confirm if your issues are gone, restoring the option "top edge styling" to "new style"
Thanks!
(PS: issue #295 was the same cause and have this same fix)
