### ISSUE TITLE
[FIXED in ver 303] - Original Min/Max/Close buttons don't appear.

### ISSUE THREAD

**Issue by ToastyYogurtTime** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#295]
As of the most recent update, having custom Min/Max/Close buttons off has the Min/Max/Close buttons missing entirely, with a space made for their place. The custom buttons work fine, but I like the look of Windows 10's Min/Max/Close buttons on the Firefox Dev skin.
![screenshot_22](https://cloud.githubusercontent.com/assets/14959006/10265770/aca42d46-6a03-11e5-81d3-4dbe3653a918.png)
Pictured is part of the nav bar with custom buttons off, that big space to the right is where the Min/Max/Close buttons should be.

**Comment by Gaffer13** [comment]
It can be a conflict with one or more extensions. I had the same issue with Tree Style Tab - but everything was fine with a clean profile. 

As a temporary workaround, set top edge styling to "Legacy" in advanced settings.

**Comment by ToastyYogurtTime** [comment]
That fixed it for now. Thanks.

**Comment by Javier-DarthPalpatine** [comment]
This is hopefully FIXED in all cases in new version 303rc & 303 !
Please confirm if your issues are gone, restoring the option "top edge styling" to "new style"
Thanks!
(PS: issue #293 had the same cause and have this same fix)

**Comment by Gaffer13** [comment]
Yes, the issue is fixed for me. Thank you very much!

**Comment by ToastyYogurtTime** [comment]
Issue is fixed for me as well. Thank you!
