### ISSUE TITLE
Firefox window can't be moved by dragging unless a Persona skin is installed.

### ISSUE THREAD

**Issue by vovcacik** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#296]
Hi,
in normal mode I can drag and move window by dragging the *empty* space between UI elements (buttons, inputs etc.). However this does not work at all for private browsing windows.

Thanks

**Comment by vovcacik** [comment]
I've found out this is not related to private browsing but to Persona skins. If I don't have Persona skin installed, dragging the window does not work, no matter what mode (normal/private browsing) I am in.

However private browsing disables Persona skin, so the bug is better apparent in that mode.

**Comment by PimpUigi** [comment]
I also can't drag the window at all using the caption area. Skin or no skin.

**Comment by PimpUigi** [comment]
Testing which versions let me drag the window by the caption bar, I had to go all the way back to
Version 2.9.8rc Released September 3, 2015 295.1 kB 

Which coincidentally also fixed where my min/max/close stuff was appearing; however I use the following stylish code *combined* with the Small Caption Bar option, so YMMV. (and this is the same for w10 and w.8.1)

    #hcp-caption-box {
        margin-top: -3px !important;
    }
    
    #hcp-title-box-label {
        visibility: collapse !important;
    }
    
    #hctp-controls-top-fixed {
        margin-top: 1px !important;
        margin-right: -2px !important;
    }

**Comment by vovcacik** [comment]
I am on Windows 8.1 and Windows 10, addon version 3.0.3.1, but I had this problem for very long time, year or maybe longer.

**Comment by Javier-DarthPalpatine** [comment]
Here under **Windows 7 - 64**, I *can* drag window by custom-caption and some empty spaces I've tested!.  I'll try to test under Win8 & 10 soon.
Could you test this in Win7 too? (will help spotting the bug)
-
 PimpUigi, about the mmc buttons, just to be sure: are you using the option:  Advanced > "Top Edge ... internal styling" --> "New Style .." right?

**Comment by PimpUigi** [comment]
Yes, "new style". But, I was able to fix my dragging issue with the following code.

    @namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul); 
    @-moz-document url(chrome://browser/content/browser.xul) {


    #hcp-caption-box {
        margin-top: -3px !important;
        margin-left: -1000px !important;
    }
    
    #hctp-controls-top-fixed {
        margin-top: 4px !important;
        margin-right: -2px !important;
    }
@media all and (-moz-windows-theme:aero) {

#hctp-controls-top-fixed {
    margin-top: -3px !important;
    margin-right: -2px !important;
}
}
}

**Comment by vovcacik** [comment]
@Javier-DarthPalpatine I have tested the this on Windows 7 x86 now and it is the same as on Windows 8.1 x64 and Windows 10 x64 as tested previously.

Steps to reproduce:
- create new Firefox profile on Win 7, 8.1, 10
- run the firefox and install HCTP 3.0.5
- open private browsing window
- try to drag the window by *the few pixels above and below the address input field*

Expected: the window can be dragged
Actual: window isn't dragged

Workaround: install [Private Browsing Personas][pbp] and repeat steps since opening the private window. The window will get dragged this time.

[pbp]: https://addons.mozilla.org/en-US/firefox/addon/private-browsing-personas/

**Comment by vovcacik** [comment]
This issue is still valid, but now overshadowed by #312

**Comment by vovcacik** [comment]
As of Firefox 47 we lost the ability to drag the window by free space in tabbar completely. That makes this issue obsolete. 
@Javier-DarthPalpatine believes its due to major update to Firefox UI and I don't think reimplementing is worth the time (you could probably count people using that feature on one hand). For details see #312
