### ISSUE TITLE
Problem with multi-process Firefox Developer Edition

### ISSUE THREAD

**Issue by flat-linex** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#301]
It seems to me that when this extension is enabled together with the multi-process functionality of Firefix developer edition I cannot see flash blocks in, e.g., http://osservatorio.energia.provincia.tn.it/apeoe/

Thanks,

**Comment by vovcacik** [comment]
I can't see any flash blocks at the italian webpage regardless this addon is installed or not. On contrary I can see flash running at [adobe site](http://www.adobe.com/software/flash/about/) without any problem with this addon.

Let's close this?

**Comment by flat-linex** [comment]
Fine with me.

Thanks.

On Tue, Mar 22, 2016 at 11:14 AM, Vlastimil Ovčáčík <
notifications@github.com> wrote:

> I can't see any flash blocks at the italian webpage regardless this addon
> is installed or not. On contrary I can see flash running at adobe site
> <http://www.adobe.com/software/flash/about/> without any problem with
> this addon.
>
> Let's close this?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus/issues/301#issuecomment-199735007>
>



-- 
You cannot manipulate a marionette with only one string -The Zensunni Whip
(Frank Herbert, Dune)

g+      >> http://bit.ly/M25XDX / http://bit.ly/M2bx9o
twitter >> https://twitter.com/#!/flat__line
web    >> http://osservatorio.energia.provincia.tn.it

my last contribution to the Computer Vision community: Template Matching
Techniques in Computer Vision <http://bit.ly/T1XZT3>

**Comment by Javier-DarthPalpatine** [comment]
Thanks!
