### ISSUE TITLE
Feature Request: Zoom In/Zoom Out on Wheel Scroll

### ISSUE THREAD

**Issue by spideymouse** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#302]
Hi Javier,

Great work on the new features for the Firefox and Close buttons. The added functionality is great. My request is the added option to Zoom In/Zoom Out for the existing wheel gestures Wheel, Wheel left and Wheel right. The secondary function (with Shift Key down) could be Page Up/Down. Let me know what you think!

Best Regards,
Tim

**Comment by Javier-DarthPalpatine** [comment]
Hi Tim! 
DONE!  in  Version 3.0.5 

This was a very nice feature that was missing. Maybe there's is some other exciting features waiting to be discovered and added !  :-)
Regards!
J

**Comment by spideymouse** [comment]
Awesome! Keep up the great work!

Tim

**Comment by Javier-DarthPalpatine** [comment]
Thanks!
J
