### ISSUE TITLE
Feature Request: "Enable Using a Non-Glass Like Background"

### ISSUE THREAD

**Issue by PimpUigi** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#305]
We have 3 options right now, 
1.1 Using a glass like background
2. Same appearance for testing
3. Another option for testing

Well, how about we make one of those a Non-glass like background. Just one solid color for the Windows 8 and Windows 10 users?

Glass didn't look good anyway. Windows 7 go bye bye!

**Comment by vovcacik** [comment]
How would glass-like and non-glass-like background differ? Just wondering...

**Comment by PimpUigi** [comment]
One would just be a simple matte color. Like how they are in windows 8 / windows 10.

**Comment by Javier-DarthPalpatine** [comment]
DONE in version 3.0.6rc.  
Please let me know if there is any further issue
Tks!
