### ISSUE TITLE
Can't drag the Fx window with caption bar

### ISSUE THREAD

**Issue by PimpUigi** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#306]
Testing which versions let me drag the window by the caption bar, I had to go all the way back to
Version 2.9.8rc Released September 3, 2015 295.1 kB 

Which coincidentally also fixed where my min/max/close stuff was appearing; however I use the following stylish code *combined* with the Small Caption Bar option, and Classic Theme so YMMV. (and this is the same for w10 and w.8.1)

    @namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul); 
    @-moz-document url(chrome://browser/content/browser.xul) {
   
    #hcp-caption-box {
        margin-top: -3px !important;
    }
    
    #hcp-title-box-label {
        margin-top: 1000px !important;
    }
    
    #hctp-controls-top-fixed {
        margin-top: 1px !important;
        margin-right: -2px !important;
    }
	@media all and (-moz-windows-theme:aero) {
    
    #hctp-controls-top-fixed {
        margin-top: -3px !important;
        margin-right: -2px !important;
    }
    }
    }

**Comment by vovcacik** [comment]
This is related to #312, which besides the broken draggability of caption bar deals with same issue with free space in toolbar.

**Comment by Javier-DarthPalpatine** [comment]
* I've commented & posted a FIXED version in issue #312. Please let me know if there is any further issue in this.
Thanks!
J

**Comment by vovcacik** [comment]
I can confirm the fix, HCTP 3.0.8pre3 on Firefox 47, Win 8.
