### ISSUE TITLE
[DONE in Version 3.2.1rc  (Devel. Channel)] - Feature Request: new "Smaller Tabs & Tab Bar" option - (full height Classic tabs) 

### ISSUE THREAD

**Issue by pmusial** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#316]
Can you add an option to change tab look from Australis to Classic (exactly like "Small, almost classic Tabs" option in "Smaller Tabs & Tab Bar" but without changing the height of a tab)?

**Comment by Javier-DarthPalpatine** [comment]
DONE in Version 3.2.1rc  (@ Devel. Channel)
