### ISSUE TITLE
[FIXED in Ver 3.0.10] - Can't click on tabs, stopped working today - [Fx 46 or earlier]

### ISSUE THREAD

**Issue by pixelwiz** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#318]
Worked great for years, all of a sudden, I saw the browser blink (maybe it updated?) running version 46.0.1 now, but I can't click on the tabs anymore.  I can maximize and close the browser, those buttons work, the bookmarks work, but I can't switch tabs by clicking on them.  Disabling your add-on fixes that issue but than that space-wasting top bar comes back.  Can you please check/fix?

**Comment by BirdTurgler** [comment]
Same problem here. Tried messing around with the settings but the only thing that fixed it was disabling the addon entirely.

**Comment by yiannis0030** [comment]
I have the same issue after I got the new update!! :(

**Comment by Javier-DarthPalpatine** [comment]
I'm, checking this.
Are you all on Windows right? (not Linux)
Could anybody please upload a screenshot when the issue happens?  Is the tabbar area + mmc buttons like messed up?
Tks!

**Comment by BirdTurgler** [comment]
Yeah, currently on Windows 7.

Tab bar, custom firefox button and mmc buttons look exactly like normal, only difference is clicking/hovering does nothing. When the window isn't maximized the firefox button and mmc buttons work, but tabs still don't.

http://i.imgur.com/S7PtCEQ.gif

**Comment by Javier-DarthPalpatine** [comment]
I still can't reproduce this issue.  
(Working ok here in Fx47, 49, 50-Nightly on Win7, Win 10  & Linux Mint)

Could you please confirm your environment?:
- Fx version (are all of you using a pre-47 Firefox?)
- Windows version
- HCTP version (should be **3.0.9**,  you can try also **3.0.9.1rc** but should be the same)
- If you can, please test with a NEW/CLEAN profile (instructions to EASILY do this in addon page -> "Developer-Comments")

**Comment by BirdTurgler** [comment]
Okay, just tested with a new profile and it started out working fine. So I went through the options one by one setting them to my regular settings and found the one causing the problem. It's the checkbox under "Drag-Window capability options"

As soon as I enabled that tabs stopped working. Double checked by going back to my regular profile and unchecking that box and suddenly everything works again.

**Comment by BirdTurgler** [comment]
Hmm, seems like it has something to do with using an old version of Firefox. Apparently I was still using Firefox 43, so I just tried installing the latest version to try it out and enabling that option doesn't break everything.

**Comment by Javier-DarthPalpatine** [comment]
**Bingo!** that's it!  Tks!
To Fix go to: **Advanced Settings -> "Drag Fx window using Tab-bar background" -> leave UNCHECKED (default value)!**

This issue seems to appear only in Firefox 46 or earlier.
**Definitive Fix in on the way!**
Tks a lot!

**Comment by yiannis0030** [comment]
Thank you very much!

That worked for me :)

Keep up the good job!
