### ISSUE TITLE
["VERTICAL MAXIMIZED improved" released in ver 3.1.4rc!] - Remote Titlebar when not in full-screen option

### ISSUE THREAD

**Issue by pixelwiz** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#321]
Hi, I've been using and loving your plugin for years.  But I just bought a bigger monitor (a lot bigger, and wider, 4k 32")  So while screen real-estate is no longer at as much of a premium as it was, I'd still like your plugin to work.  Except up until now, I've only used Firefox in Full-screen mode, however, the new monitor is wide enough to fit two applications side-by-side, so what means I can't use Firefox in full-screen mode.  And if I use the windows 10 half screen feature, to maximize it but only on one side of the screen, the header doesn't go away, so it stays like a window.  Is it possible to somehow make it work the same way it does in full-screen but when it's maximized to only half the screen?

**Comment by Javier-DarthPalpatine** [comment]
YES! it's possible.
I've tested already a solution that works! but It's still very alpha code.  Especially **tabs reach upper edge again!**
I'll try to release it at lease as a hiiden pref or something :-)
For a while already I was thinking: This will be the 1st feature especially for big screens :-)

**Comment by pixelwiz** [comment]
Awesome, thanks, can't wait to give it a try

**Comment by Javier-DarthPalpatine** [comment]
Version  3.1.4rc  is released with this!   It's called "VERTICAL MAXIMIZED improved"
Enjoy! :-)

**Comment by pixelwiz** [comment]
Awesome, where can I get that version from?

**Comment by pixelwiz** [comment]
Nice work, finally figured out how to get the RC and get the Top Edge and
some other settings changed to finally get this working, but it's great!

Thank you very much,
-Roman
