### ISSUE TITLE
[Action tooltip settings will be out very soon!] - Feature request: could we have a way of disabling the tooltips, please?

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#325]
I mean the tooltip - that shows what various mouse buttons do - which appears when the pointer is over the close button.

**Comment by Javier-DarthPalpatine** [comment]
Yes! 
It's already in next version that will be released soon!

**Comment by ACinnamonUserInUK** [comment]
That's the stuff. Brilliant.
