### ISSUE TITLE
[Fixed in  3.1.4rc] - System borders bug

### ISSUE THREAD

**Issue by MJ1979** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#327]
When using Firefox in windowed mode System borders -7 doesn't work properly. It used to work before, but currently is thicker then -6. 

I'm using latest version of Firefox on Windows 7x64

**Comment by Javier-DarthPalpatine** [comment]
New version 3.1.4rc  released, with this fixed!  
(added an extra option + better explanatory tooltip)

**Comment by MJ1979** [comment]
Thank you for the fix. It works perfectly.
