### ISSUE TITLE
[FIXED in Version 3.2.1rc  (@ Devel. Channel)] - Changing hovering activation delay-time does not take effect

### ISSUE THREAD

**Issue by spvkgn** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#332]
2000ms - it seems no change at all.

`Name of the browser (appName)    Netscape
Name of the browser vendor (vendor) 
Code name of the browser (appCodeName)  Mozilla
Engine of the browser (product) Gecko
Build number of the browser engine (productSub) 20100101
Version and platform of the browser (appVersion)    5.0 (X11)
Version of the browser given by the vendor (vendorSub)  
Build identifier of the browser (buildID)   20160919214116
User-agent request header (userAgent)   Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:49.0) Gecko/20100101 Firefox/49.0
Language of the browser (chrome-locale) ru
Language preference in the browser (useragent-locale)   chrome://global/locale/intl.properties
Cookies are enabled (cookieEnabled) true
Operating system (platform) Linux i686
Information about the OS and CPU (oscpu)    Linux i686
System is online (onLine)   true`

**Comment by Javier-DarthPalpatine** [comment]
FIXED in Version 3.2.1rc  (@ Devel. Channel)
