### ISSUE TITLE
Compatibility with Tab Groups

### ISSUE THREAD

**Issue by Quicksaver** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#333]
This add-on just doesn't look (or work?) correctly while in groups mode; see https://github.com/Quicksaver/Tab-Groups/issues/431

I believe it might be better to not hide the titlebar at all while in groups view. Is there any chance this can be done from within HCTP itself, maybe by listening to ```tabviewshown``` and ```tabviewhidden``` events fired on its frame, and enabling/disabling accordingly?

Or is there anything I can do from within Tab Groups maybe? Some event or method I can call in the window to force enable and disable hiding the titlebar?

**Comment by Javier-DarthPalpatine** [comment]
Hi Luis!
Yes I can fix it.

I'm trying this:
#tab-view-deck   #browser-panel  ~  *  {
	margin-top: 20px !important;
	-moz-window-dragging: no-drag;
}s
And It's working very well! (see sshot)
The 'no-drag' if because #titlebar (drag) can be under top zone and take over pointer events, and also to make tour iframe be safer in general.

What do You think of this solution?, Are you OK with it?
Regards!
Javier

PD: do you speak spanish? :-)   It's my mother's tongue.

![hctp tabgroups](https://cloud.githubusercontent.com/assets/1030193/19415981/d93b70d8-9358-11e6-94ee-d371b3a64299.png)

**Comment by Quicksaver** [comment]
Oh, that's very nice, I didn't think to add a margin to the frame itself. I was trying all sorts of tricks for the titlebar in my stylesheet before, never even occurred to me the simplest thing it seems. 😄 

The screenshot made me think about the button on the top left being visible in groups view. On the one hand, some actions could be useful (exit application, open new window...). On the other, most of its actions are page specific, and could lead to some confusion when trying to use them in there; all of them should still *work*, they just might not produce immediately visible results. It's nothing critical though, just a thought that popped in my head.

What do you think? I personally could see it staying or not appearing either way.

> PD: do you speak spanish? :-)

No, sorry, I'm portuguese. I can understand some spanish, but definitely not enough to speak it. :)

**Comment by Javier-DarthPalpatine** [comment]
Great!
It's out already in versions 315rc  and  315 !!

About top-left button: I leaved it for the time being. Have to think that better. Thanks for mentioning it!

I understand (and can barely speak) portuguese (Brazilian)! :-)

Obrigado!
Javier

**Comment by Javier-DarthPalpatine** [comment]
Closing issue due to main reason fixed.  But please all feel free to continue commenting.
