### ISSUE TITLE
l10n: "Other:" can't be translated

### ISSUE THREAD

**Issue by yfdyh000** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#335]
\hidecaptionplus-dp@dummy.addons.mozilla.org\chrome\australis\content\opt_other.xul(60):  <groupbox> <caption><label> Other: </label></caption>

**Comment by Javier-DarthPalpatine** [comment]
Right! hehe.   I'll handle it.
Tks for the catch
