### ISSUE TITLE
[ENABLED in Version 3.2.1rc @ Devel-Channel!] - support for Multi-Process (e10s) Firefox

### ISSUE THREAD

**Issue by ludovicaelbrecht** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#338]
Hi,

This addon is currently not marked as compatible with Firefox's new multiprocess (aka electrolysis / e10s) model. e10s will become enabled by default pretty soon.

See https://www.arewee10syet.com/ and https://wiki.mozilla.org/Electrolysis for more info.

Any plans to support e10s? Or to rewrite the addon as WebExtensions (given that XUL is deprecated), which will also make it work with e10s?

Thanks,
Ludovic

**Comment by Javier-DarthPalpatine** [comment]
Yes, I'm testing already since a time ago an **enabled e10s version**!, and if all latest tests are OK,  I'll upload it at Devel-Channel . 
(And bc of the adjusted code used, I'm not expecting any issue at all with e10s)

**Comment by Javier-DarthPalpatine** [comment]
It's released!
ENABLED e10s in Version 3.2.1rc @ Devel-Channel!
