### ISSUE TITLE
Close button should close on mouse *Click* not on mouse *Press*

### ISSUE THREAD

**Issue by jtechpro** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#340]
The firefox close button when it is set to close the firefox window (which is its default action), it must close the firefox on **click** not on **press**.

The other two buttons, minimize and maximize are working fine. The problem is only with close button.

Fix this immediately.

**Comment by Javier-DarthPalpatine** [comment]
That can be configured thru "More Options" button :-)

**Comment by jtechpro** [comment]
Ok. Done. Thanks.
