### ISSUE TITLE
[See new url address here & at home page] - Babelzilla

### ISSUE THREAD

**Issue by Sacredwheels** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#357]
Hi.
Why is HCTP absent on Babelzilla now?

**Comment by Javier-DarthPalpatine** [comment]
Hi!
beta.babelzilla  url address isn't working!, but they put an alternative here:!

http://adofex.clear.com.ua/projects/p/Hide_Caption_Titlebar_Plus/
