### ISSUE TITLE
[PALEMOON] [Very old hctp version]  Clipped Close-Min-Max buttons: #titlebar-buttonbox-container.

### ISSUE THREAD

**Issue by UserPATRICKJANE** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#358]
Using Pale Moon 27.3.0 the button container is clipped, cropped, when titlebar is hidden and there are no custom buttons (re "Fx. default"), which is when the buttons are standard size.

The following 3px right-padding fixes it (#titlebar-buttonbox-container), and the margin-right 10px for #urlbar gives a bit of space between the button container and url bar

#titlebar-buttonbox-container
{
padding: 0px 3px 0px 0px;
}

#urlbar
{
margin-right: 10px !important;
}

**Fixed:**
![Fixed with above styling](https://user-images.githubusercontent.com/30115536/28116055-445198dc-66ff-11e7-9c13-a1a3397e815b.png)

**Broken, clipped:**
![Broken, clipped, without above styling](https://user-images.githubusercontent.com/30115536/28116056-4451f1f6-66ff-11e7-8fbe-3f2e0eb5bb5b.png)

**Location, relevant section, in addon UI:**
![Location of the active section in addon UI](https://user-images.githubusercontent.com/30115536/28116054-444f915e-66ff-11e7-846e-713132278e90.png)

**Comment by Javier-DarthPalpatine** [comment]
Well, thar HCTP version (by seeing the dialog) is very old already.  

I *am testing* the newer version in Palemoon and it works pretty well (didn't check all stayle details), *but* It has an issue at Firefox shutdown/restart.  I'll publish it here soon and I'll let you know!
