### ISSUE TITLE
[Same as Fixed issue #339 ?] - Not working on Portait monitor at 1920x1200 res

### ISSUE THREAD

**Issue by rsmolkin** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#359]
Hi, for some reason this plugin is having issues when I try to use it on a 1920x1200 monitor in portrait setup.  See screen grabs attached, but the top part just disappears.

Enabled:
https://snag.gy/fMPxBo.jpg

Disabled:
https://snag.gy/cDnUQG.jpg

![canvas2](https://user-images.githubusercontent.com/28454845/28579196-eabb70ce-7129-11e7-8ada-12f87cbef037.png)
![canvas1](https://user-images.githubusercontent.com/28454845/28579197-eaf296ee-7129-11e7-9fb8-9e26b07fb520.png)

**Comment by Javier-DarthPalpatine** [comment]
Is this happening on a secondary monitor (multiple monitor mode)?
I think this is the same as issue #339 , and It was just fixed in new version 3.2.8rc
Please give it a try!

**Comment by rsmolkin** [comment]
Yes, it was.  Seems to be ok now, but it's actually been ok for a while, not sure if it was a version change from you cause I didn't update it, unless it updates automatically, or something with the browser that got updated, or the os.  but main point is, it seems to be working ok now.  Thanks.
