### ISSUE TITLE
[New! Custom-mmc-skins in ver 3.2.10rc] [Feature Request] KDE Breeze Dark Buttons (provided code and SVGs)

### ISSUE THREAD

**Issue by RaitaroH** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#366]
Would be nice to have kde buttons in firefox with your extension. I have used your win10 css file as a base and managed to do this rather well. My only problem is that I cannot make SVG stacking work so there is some lag when fetching the hover images (removed background-color for hover effect). I modified the size of the icons, their padding too.

As of now I am using it as userChrome.css file and works well.

I have added everything you would need to look at in my repo here:
https://github.com/RaitaroH/Vertex-Breeze-Metacity/tree/master/chrome

**Comment by Javier-DarthPalpatine** [comment]
Great!  It's working already here.
I'm adding **new CUSTOM options to 'mmc skins'!**, using external css files.  (same as for sounds and fx button images)
Thanks!

**Comment by Javier-DarthPalpatine** [comment]
About the lag fetching images:
I think You could merge all svg files into one svg for each button, like in here:
[hctp]\chrome\skin\caption-buttons.svg  (copied from firefox)
and using "#" in the url like "caption-buttons.svg#close-white" and so on.

**Comment by RaitaroH** [comment]
Oh, wow you actually will add this to the addon! Nice. Thank you very much.

Also regarding the svg stacking... I have tried that because I saw it in the code. I am not sure what I am missing but if I stack them only the image on top appears. I also tried different layers and changing the opacity... Maybe are the svgs too complex or I am doing something wrong? If you can maybe try to stack the svgs, you can find them all in my repo. Also, the lag is not too bad, but it is noticeable. Not that big of a problem. Maybe if you have time to fix it.

Thank you again.

**Comment by Javier-DarthPalpatine** [comment]
BINGO! :-)  
  <style>
    g:not(:target) {
      display: none;
    }
  </style>

Here a working example!  (svg cleaned before I've got it working)
[min_test_2_layers.zip](https://github.com/Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus/files/1326959/min_test_2_layers.zip)

**Comment by Javier-DarthPalpatine** [comment]
I have a HCTP release ready.   Also a working copy of a much simpler custom1.css that I'll put here.

**Comment by Javier-DarthPalpatine** [comment]
**Custom Min,Max,Close buttons** feature is out with new HCTP version **3.2.10rc**,  in Development Channel
(using external css files)

**Also the 1st working example of  Custom-mmc-buttons  is here!:**
[Vertex-Breeze__for_hctp.zip](https://github.com/Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus/files/1327000/Vertex-Breeze__for_hctp.zip)

**Comment by Javier-DarthPalpatine** [comment]
This example has a much simpler custom1.css, and slightly modified SVG files (stroke width), for you to consider! :-)

**Comment by Javier-DarthPalpatine** [comment]
New feature option + results:
![mmc_custom_tt](https://user-images.githubusercontent.com/1030193/30778995-386140fe-a0b1-11e7-9d45-f7e792bd569b.png)

In Linux:
![mmc_custom_tt_linux](https://user-images.githubusercontent.com/1030193/30779000-4e4046d6-a0b1-11e7-86e7-2c3857f8b56e.png)

![mmc_custom1](https://user-images.githubusercontent.com/1030193/30779002-5957628e-a0b1-11e7-9230-776af3d64e2d.png)

**Comment by RaitaroH** [comment]
Awesome!
So you have to put the custom.css file in your ~/Documents huh? I would have thought you would put it in your firefox profile but your call. Also nice that you managed to stack the svgs.
Thank you for implementing this! I eagerly await the official update. I am sure other KDE fans/users will really love this feature. I sure do.
