### ISSUE TITLE
Firefox 57 support

### ISSUE THREAD

**Issue by munim** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#367]
Hi @Javier-DarthPalpatine,

Firstly, thanks for this awesome plugin for firefox. This is a must-have for many Linux users.

As you already know that Firefox 56 is getting released and Firefox 57 will hit beta channel and all legacy plugins will stop working.

Do you've any plan to support WebExtensions API for this plugin?

**Comment by Javier-DarthPalpatine** [comment]
Hi!
I've opened the thread #354 explaining all this.   In short: HCTP won't die!
