### ISSUE TITLE
[PALE MOON + new HCTP included here] [BUG, cause detected!, needs research!] - [PaleMoon 27.5 / 27.4.2] & [Firefox 43]  *HANGS* at shutdown or restart, also on addon disable/uninstall.

### ISSUE THREAD

**Issue by Javier-DarthPalpatine** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#368]
New HCTP for PALE MOON: there is a bug that need research!: 
**Update: offending HCTP code already detected!, see details below**

**[PaleMoon 27.5 / 27.4.2]  and  [Firefox 43]**  **HANGS** at shutdown or restart  with this addon latest version enabled! (copy included here!)
Such browser also HANGS on addon disable/uninstall (but a special alert message appears for choosing to avoid hanging)
For hanging, "Vertical Maximize" must be on.
	
The fact that it also hangs **Firefox 43** may be a good clue to solve this.
In Firefox 52 thru 56 addon works ok.

Technical details: 
**Update: offending HCTP code already detected!**:  
Just look for "WhatIsHang.exe" in the code to see details, plus commented code to **manually hang** such a browser.
Also, there is a special flag to avoid hanging at all:  In the js console put:
` window.Services.hcDisableHang=true `

Here is the special copy of HCTP enabled for Pale Moon! 
[hidecaptionplus-3211-2testPM__xpi.ZIP](https://github.com/Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus/files/1381200/hidecaptionplus-3211-2testPM__xpi.ZIP)

PS: Info posted also in Pale Moon forum!
[https://forum.palemoon.org/viewtopic.php?t=17009](https://forum.palemoon.org/viewtopic.php?t=17009)

**Comment by Javier-DarthPalpatine** [comment]
Technical Info: (Win 7 64)

        From hanged Pale Moon:

```
Description:
  A problem caused this program to stop interacting with Windows.
Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	palemoon.exe
  Application Version:	27.5.0.6474
  Application Timestamp:	59c56e74
  Hang Signature:	95b6
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Hang Signature 1:	95b65b787ec982f99e2c0b3944970652
  Additional Hang Signature 2:	7486
  Additional Hang Signature 3:	7486fb66cadf5712e934e00747705234
  Additional Hang Signature 4:	95b6
  Additional Hang Signature 5:	95b65b787ec982f99e2c0b3944970652
  Additional Hang Signature 6:	7486
  Additional Hang Signature 7:	7486fb66cadf5712e934e00747705234
```

        From hanged Firefox 43:
```
Description:
  A problem caused this program to stop interacting with Windows.
Problem signature:
  Problem Event Name:	AppHangB1
  Application Name:	firefox.exe
  Application Version:	43.0.1.5828
  Application Timestamp:	56722c0f
  Hang Signature:	965a
  Hang Type:	0
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Hang Signature 1:	965ae10e2cde2205a0b0f112f7087e9a
  Additional Hang Signature 2:	5dd0
  Additional Hang Signature 3:	5dd01a73905e22692a14a125cc6e0c03
  Additional Hang Signature 4:	965a
  Additional Hang Signature 5:	965ae10e2cde2205a0b0f112f7087e9a
  Additional Hang Signature 6:	5dd0
  Additional Hang Signature 7:	5dd01a73905e22692a14a125cc6e0c03
```

**Comment by Javier-DarthPalpatine** [comment]
**UPDATE: cause detected!**, main messages updated!

**Comment by JustOff** [comment]
Thank you for your efforts to provide a modern version of HCTP for Pale Moon and I hope to see your very useful add-on listed on the [Pale Moon Add-ons Site](https://addons.palemoon.org/extensions/) soon!

Ping @Lootyhoof, @FranklinDM.

**Comment by rea987** [comment]
I confirm that bug affected Pale Moon 27.6.2 (64-bit) on Ubuntu Mate 17.10 which uses MATE 1.18.0 desktop environment.

**Comment by Lootyhoof** [comment]
Just as an FYI: We now have a self-service panel, over here: https://addons.palemoon.org/panel. With this you can upload add-ons for [Pale Moon](http://www.palemoon.org), [Basilisk](http://basilisk-browser.org) and/or [Interlink](http://binaryoutcast.com/projects/interlink/) (the latter two use the Firefox and Thunderbird GUIDs respectively). If ever it's of interest, uploading an add-on to the panel will make it show on whichever add-ons site it's relevant for. All of these applications only support XUL extensions, not WebExtensions.

Apologies for the noise in any case.
