### ISSUE TITLE
palemoon 28

### ISSUE THREAD

**Issue by porosjp** [Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus#378]
HI
Does HCTP works in PaleMoon 28.2?
If it works, were can I download it?
Thanks

**Comment by VLM-TechEd** [comment]
If you install the Classic Add-ons Archive here: https://github.com/JustOff/ca-archive/releases, you will find this and many other "outdated" Firefox add-ons. Some will work fine in PM; this one does.

It provides an icon, which you can place wherever you wish. Click on the icon, then search for the extension. Note that a separate link to each version history page appears in small text in the lower right-hand corner of each listing.

**Comment by porosjp** [comment]
Thank you very much
the extension works and the archive is a real gold mine

**Comment by VLM-TechEd** [comment]
I agree, and you are most welcome!

 

May I suggest that you set that extension not to update automatically. I realize the development on this was stopped some time ago, but still, ya never know what might happen, and later versions are out there (as indicated in the archive). 

 

Best regards,

 

Elchanan

**Comment by Javier-DarthPalpatine** [comment]
Hi!
**HCTP Development IS STILL ON** and will continue to update!!
Latest version (now 4.2.0) is always at 
    **[http://tiny.cc/hidec/](http://tiny.cc/hidec/)**
(now moved to thunderbird addons page)  :-)
And I have almost ready to upload a new 4.2.1 version!!, For Fx up to 60 Devel Ed.
